### ISSUE TITLE
Regression: passes watch dir to py.test

### ISSUE THREAD

**Issue by blueyed** [joeyespo/pytest-watch#53] opened 2016-04-07 18:05 UTC
With `ptw dir -- path/to/test_file.py` ptw will include the `dir` in the py.test run:

    Running: py.test dir path/to/test_file.py

This however will cause py.test to run the whole directory, and not only the specified test file.

This was not the case with 3.10.0, which does:

    Running: py.test path/to/test_file.py

btw: I found the best method is to specify `testpaths = path/to/tests` with the pytest options in `setup.cfg`, which gets used when running just `py.test`.

If this was done intentionally, I think it should only get done when there are no py.test args provided, but that feels a bit too magic.

**Comment by joeyespo** [comment] 2016-04-08 19:20
Yeah, this was intended (see ede80ffa64f52570658aa82dd20162e2c9a6439c, also motivated by forwarding `--ignore` to pytest from #48).

Thinking more about it though. Here's the parameter-passing use cases I was thinking of:

1. Run from subdirectory, watching and collecting tests from all subdirectories:
   - Formerly `ptw myproject -- myproject`
   - Currently `ptw myproject`

2. Ignore unrelated dirs from watch and test collection (due to large trees slowing things down):
   - Formerly `ptw --ignore tmp -- --ignore tmp`
   - Currently `ptw --ignore tmp`

   Or from a subdirectory:

   - Formerly `ptw myproject --ignore myproject/tmp -- myproject --ignore myproject/tmp`
   - Currently `ptw myproject --ignore myproject/tmp`

   (This actually was never implemented, which I forgot about! Just opened #56 to address this.)

3. Include watched directories without collecting tests from them
   - Formerly `ptw myproject mytests -- mytests`
   - Currently not possible (`ptw myproject mytests -- --ignore myproject` doesn't work)

4. Include test collection from a directory without watching them
   - Formerly `ptw myproject -- myproject mytests`
   - Currently `ptw myproject -- mytests`

(1)-(3) re-runs the tests when changing either source code or test files.

(4) only re-runs when changing source code, which doesn't seem that useful.

So the issue is that (3) isn't possible now. Is it really a problem though? It almost seems like a pre-optimization to try to exclude test collection from a watched directory. Remember, watchdog also has to crawl through a huge directory, so you'll have delay for huge project directories regardless. A better fix might be to exclude the things that aren't testable from both (static and template files for websites,`vendor` directories, etc.)

Or is there another case I'm leaving out?

**Comment by blueyed** [comment] 2016-04-08 19:49
I am using `testpaths = path/to/tests`, so there is no need to pass `path/to/tests` to py.test.

So with `ptw path`, `path` would be watched, but only `path/to/tests` used to collect tests.

If you want to keep the current behavior, then the `testpaths` option should be looked at and only if it's not used the watch directory should be passed explicitly to `py.test`?

**Comment by joeyespo** [comment] 2016-04-08 20:10
> So with ptw path, path would be watched, but only path/to/tests used to collect tests.

If you pass arguments to `py.test`, does that overwrite `testpaths`?

**Comment by joeyespo** [comment] 2016-04-08 20:12
Btw, I'm also considering having pytest-watch be usable as a standard pytest plugin. Making the command line arguments more consistent with pytest was a first step. (Just opened #57 to dedicate to that discussion.)

**Comment by blueyed** [comment] 2016-04-08 22:53
> If you pass arguments to py.test, does that overwrite testpaths?

Yes.

**Comment by joeyespo** [comment] 2016-04-09 00:24
Ah, that's a shame.

The idea is that `ptw dir` is to tell both watchdog and pytest to start their search from there. Some more questions for you:
- Are you able to run `ptw` from your project root instead of specifying where to watch and where to collect tests? If not, is it because:
  - Your tests are located outside of the project?
  - It's taking too long to boot?
- Are you able to run `cd dir && ptw` instead?

**Comment by blueyed** [comment] 2016-04-09 17:33
> Ah, that's a shame.

Only in this context, right?  Because otherwise it's quite nice, isn't it?

While I could workaround this behaviour change, I'd rather not do so.. :)

> Are you able to run ptw from your project root instead of specifying where to watch and where to collect tests? 

Yes, but I'd like to avoid scanning everything (build dir, venv etc).  Even the project's source can be skipped.  That's why I like `testpaths`.

> Are you able to run cd dir && ptw instead?

Yes.

What speaks against using the same behaviour regarding `testpaths` as py.test though?

**Comment by joeyespo** [comment] 2016-04-10 15:38
> Only in this context, right? Because otherwise it's quite nice, isn't it?

Yeah. More like it's a shame that I overlooked that option / missed your use case. Was mostly asking these questions to make sure I didn't miss something else.

Thinking more about it, I suppose (3) is important after all to keep test runs lightning fast. Perhaps a new named argument could be used for watching without collecting tests. This would continue to make sense if pytest-watch was used as a pytest plugin.

As for the case you've pointed out, what do you think of having an equivalent config option pytest-watch? Say, `watchpaths` under the `[pytest-watch]` category. Like [testpaths](https://pytest.org/latest/customize.html#confval-testpaths), it wouldn't have any effect when passing in `<dir>` arguments. Then you could run `ptw` with *no* arguments and fully customize what paths to watch and what paths to collect tests from.

**Comment by blueyed** [comment] 2016-04-18 12:17
@joeyespo 
> As for the case you've pointed out, what do you think of having an equivalent config option pytest-watch?

Sounds good to me!

**Comment by joeyespo** [comment] 2016-05-19 04:18
Just opened #61 to address this. Closing as per [this comment](https://github.com/joeyespo/pytest-watch/issues/53#issuecomment-207583557). Feel free to re-open if you don't think that'll be enough.

**Closed by joeyespo** 2016-05-19 04:18 UTC
